sign_use = {
    "0":  "Speed limit 20 km/h – Maximum speed allowed is 20 km/h",
    "1":  "Speed limit 30 km/h – Maximum speed allowed is 30 km/h",
    "2":  "Speed limit 50 km/h – Maximum speed allowed is 50 km/h",
    "3":  "Speed limit 60 km/h – Maximum speed allowed is 60 km/h",
    "4":  "Speed limit 70 km/h – Maximum speed allowed is 70 km/h",
    "5":  "Speed limit 80 km/h – Maximum speed allowed is 80 km/h",
    "6":  "End of speed limit 80 km/h – Speed restriction ends",
    "7":  "Speed limit 100 km/h – Maximum speed allowed is 100 km/h",
    "8":  "Speed limit 120 km/h – Maximum speed allowed is 120 km/h",

    "9":  "No overtaking – Vehicles are not allowed to overtake",
    "10": "No overtaking for trucks – Heavy vehicles cannot overtake",
    "11": "Priority at next intersection – You have priority",
    "12": "Priority road – Vehicles on this road have priority",
    "13": "Yield – Give way to other vehicles",
    "14": "Stop – Vehicle must come to a complete halt",
    "15": "No vehicles – Entry prohibited for all vehicles",
    "16": "Vehicles over 3.5 tons prohibited – Heavy vehicles not allowed",
    "17": "No entry – Entry is prohibited",
    "18": "General caution – Be alert and slow down",
    "19": "Dangerous curve left – Sharp curve to the left ahead",
    "20": "Dangerous curve right – Sharp curve to the right ahead",
    "21": "Double curve – Series of curves ahead",
    "22": "Bumpy road – Uneven road ahead",
    "23": "Slippery road – Road may be slippery",
    "24": "Road narrows on the right – Width of road reduces",
    "25": "Road work – Construction or repair work ahead",
    "26": "Traffic signals – Signal lights ahead",
    "27": "Pedestrians – Pedestrian crossing ahead",
    "28": "Children crossing – School zone / children crossing",
    "29": "Bicycles crossing – Watch for cyclists",
    "30": "Beware of ice/snow – Risk of icy or snowy road",
    "31": "Wild animals crossing – Animals may cross road",
    "32": "End of all speed and passing limits – Restrictions lifted",
    "33": "Turn right ahead – Mandatory right turn",
    "34": "Turn left ahead – Mandatory left turn",
    "35": "Ahead only – Go straight only",
    "36": "Go straight or right – Either direction allowed",
    "37": "Go straight or left – Either direction allowed",
    "38": "Keep right – Vehicles must keep right",
    "39": "Keep left – Vehicles must keep left",
    "40": "Roundabout mandatory – Vehicles must follow roundabout",
    "41": "End of no overtaking – Overtaking allowed again",
    "42": "End of no overtaking for trucks – Trucks may overtake again"
}
